### ISSUE TITLE
Where can I read system prompts?

### ISSUE THREAD

**Issue by franciscoabenza** [Ag2S1/Sibyl-System#1]
Please can you share a bit more about the agents instructions?

**Comment by Ag2S1** [comment]
The technical details document and related materials are being organized, and I will release them as soon as possible. The overall architecture is already disclosed in the README.

**Comment by franciscoabenza** [comment]
Please keep me updated

**Comment by Ag2S1** [comment]
@franciscoabenza Hi, the prompt has been uploaded, and we have released a technical report https://arxiv.org/abs/2407.10718
